let language = localStorage.getItem("nvm-language") === "en" ? "en" : "zh";
const L = (zh, en) => ({ zh, en });
const t = value => value[language];

const phases = {
  off: { number:"01 / POWER-OFF", title:L("在已驗證的 shutdown 條件下，沒有 powered reconstructed root","No powered reconstructed root remains under the validated shutdown condition"), text:L("Ciphertext、helper data、lifecycle state 與 SRAM device mismatch 可能持續存在；remanence 與 zeroization 仍須驗證。","Ciphertext, helper data, lifecycle state and SRAM device mismatch may persist; remanence and zeroization still require assurance."), asset:L("OTP ciphertext · helper data · lifecycle bits · device mismatch","OTP ciphertext · helper data · lifecycle bits · device mismatch"), method:L("Invasive / optical readout","Invasive / optical readout"), question:L("成功讀取後，在 composed controls 成立的條件下實際揭露什麼？","What does readout reveal when the composed controls hold?"), outcome:L("預期為 ciphertext／protected data；helper-data integrity、remanence 與 zeroization 仍是測試目標。","Expected ciphertext/protected data; helper-data integrity, remanence and zeroization remain test targets."), key:"NOT POWERED", result:"CONDITIONAL", active:false },
  boot: { number:"02 / BOOT", title:L("PUF reconstruction 建立第一個敏感時窗","PUF reconstruction creates the first sensitive window"), text:L("startup response、error correction、helper-data processing 與控制流程需要同時接受 leakage、fault 與 PVT／aging 驗證。","Startup response, error correction, helper-data processing and control flow require leakage, fault and PVT/aging validation."), asset:L("PUF response · reconstruction intermediate","PUF response · reconstruction intermediate"), method:L("Power/EM SCA · voltage/clock/EM FI","Power/EM SCA · voltage/clock/EM FI"), question:L("重建失敗能否被利用成 bypass、oracle 或降級路徑？","Can reconstruction failure become a bypass, oracle or downgrade path?"), outcome:L("失敗時 fail secure；不輸出可利用中間值。","Fail secure without exploitable intermediates."), key:"RECONSTRUCTING", result:"FAIL SECURE", active:true },
  derive: { number:"03 / DERIVE", title:L("root 與 derived key 必須縮短 residency","Root and derived keys need bounded residency"), text:L("KDF 與 AES 操作可能產生 power／EM leakage，也可能受 DFA 或 instruction-skip 類 fault 影響。","KDF and AES operations may leak through power or EM and may be exposed to DFA or instruction-skip faults."), asset:L("Root intermediate · working keys","Root intermediate · working keys"), method:L("DPA/CPA · higher-order SCA · DFA","DPA/CPA · higher-order SCA · DFA"), question:L("錯誤輸出是否可建立 key-recovery oracle？","Can faulty outputs form a key-recovery oracle?"), outcome:L("偵測錯誤、限制輸出、隔離與清除。","Detect errors, suppress outputs, isolate and clear."), key:"ACTIVE / BOUNDED", result:"NO KEY DISCLOSURE", active:true },
  access: { number:"04 / AUTHORIZED ACCESS", title:L("明文只應存在於受控 transaction 內","Plaintext belongs only inside an authorized transaction"), text:L("controller、bus、permission check、address mapping 與 reset sequence 共同決定 secure boundary 是否成立。","Controller, bus, permission checks, address mapping and reset sequencing determine whether the secure boundary holds."), asset:L("Plaintext window · access policy · bus data","Plaintext window · access policy · bus data"), method:L("Protocol abuse · glitch · debug misuse","Protocol abuse · glitch · debug misuse"), question:L("跳過一次檢查，是否足以完成未授權讀寫？","Can one skipped check complete an unauthorized transaction?"), outcome:L("policy atomicity；錯誤或 reset 不可放寬權限。","Policy atomicity; error or reset never relaxes access."), key:"AUTHORIZED WINDOW", result:"POLICY ENFORCED", active:true },
  zeroize: { number:"05 / ZEROIZE", title:L("清除必須可驗證，而且能承受中斷","Clearing must be verifiable and interruption-safe"), text:L("zeroization 不只是寫入零；必須定義觸發條件、reset／fault 行為、殘留狀態與驗證方法。","Zeroization is more than writing zeroes; define triggers, reset/fault behavior, residual state and verification."), asset:L("Residual root/working-key state","Residual root/working-key state"), method:L("Reset interruption · remanence · fault","Reset interruption · remanence · fault"), question:L("在最不利中斷點，敏感狀態是否仍可恢復？","At the worst interruption point, can sensitive state be recovered?"), outcome:L("不可恢復、reset-safe、測試結果可重現。","Irrecoverable, reset-safe and reproducibly tested."), key:"REMOVING", result:"NO RESIDUAL KEY", active:true }
};

const assuranceMaturity = [
  {name:"CLAIMED",title:L("公開主張","Public claim"),text:L("供應商公開描述功能或安全特性。","A supplier publicly describes a function or security property."),items:L(["保留原始來源與日期","不可改寫為已驗證事實"],["Retain original source and date","Do not restate as verified fact"])},
  {name:"SPECIFIED",title:L("需求已界定","Requirement specified"),text:L("資產、威脅、邊界、假設與通過條件已有文件。","Assets, threats, boundary, assumptions and pass criteria are documented."),items:L(["Threat model 與 security requirement","仍不代表測試已完成"],["Threat model and security requirement","Testing is not yet complete"])},
  {name:"TESTED",title:L("內部測試","Internally tested"),text:L("有版本化方法、環境、結果、例外與 owner。","Versioned method, environment, results, exceptions and owner exist."),items:L(["保存原始資料與重現條件","揭露 coverage 與限制"],["Retain raw data and reproduction conditions","Disclose coverage and limits"])},
  {name:"EVALUATED",title:L("獨立評估","Independently evaluated"),text:L("第三方依明確 scope 與方法審查安全性。","A third party reviews security against an explicit scope and method."),items:L(["記錄 lab、報告與 TOE","不可擴張至未評估整合"],["Record lab, report and TOE","Do not extend to unevaluated integration"])},
  {name:"CERTIFIED",title:L("正式認證","Formally certified"),text:L("scheme、level、certificate、版本與有效範圍可查。","Scheme, level, certificate, version and valid scope are traceable."),items:L(["區分 IP、SoC、device scope","logo 不等於所有攻擊皆免疫"],["Distinguish IP, SoC and device scope","A logo does not imply immunity to all attacks"])},
  {name:"FIELD-PROVEN",title:L("量產證據","Field-proven"),text:L("deployment、PVT、aging、回報與修補形成長期證據。","Deployment, PVT, aging, reports and remediation form longitudinal evidence."),items:L(["持續更新 incident 與 errata","數量不能取代適用性分析"],["Continuously update incidents and errata","Volume does not replace applicability analysis"])}
];

const roleContent = {
  foundation:[L("分辨攻擊類型","Distinguish attack classes"),L("理解 FI、SCA 與實體讀取的目的、差異和限制。","Understand the goals, differences and limits of FI, SCA and physical readout."),"CONCEPT CHECK"],
  practitioner:[L("建立 Secure NVM threat model","Build a Secure NVM threat model"),L("把 SRAM PUF、AES、OTP、controller 與 lifecycle 映射到資產和攻擊時窗。","Map SRAM PUF, AES, OTP, controller and lifecycle to assets and attack windows."),"THREAT MAP"],
  evaluator:[L("設計可重現 test campaign","Design a reproducible test campaign"),L("定義 trigger、parameter space、分類、通過條件、coverage 與 residual risk；公開頁不提供 exploit 配方。","Define triggers, parameter space, classification, pass criteria, coverage and residual risk; exploit recipes remain controlled."),"TEST PLAN"],
  decision:[L("審查證據與認證範圍","Review evidence and certification scope"),L("判斷 TOE、證據成熟度、可重用性、限制、unknowns 與產品決策風險。","Assess TOE, evidence maturity, reuse, limits, unknowns and product decision risk."),"ASSURANCE REVIEW"]
};

function applyLanguage(){document.body.dataset.language=language;document.documentElement.lang=language==="zh"?"zh-Hant":"en";document.querySelectorAll("[data-zh][data-en]").forEach(el=>el.textContent=el.dataset[language]);document.querySelector("#languageToggle").setAttribute("aria-label",language==="zh"?"Switch to English":"Switch to Traditional Chinese");document.querySelector(".brand").setAttribute("aria-label",language==="zh"?"NVM Knowledge Hub 首頁":"NVM Knowledge Hub home");document.querySelector("#primaryNav").setAttribute("aria-label",language==="zh"?"頁面導覽":"Page navigation");document.querySelector("#controlMatrix").setAttribute("aria-label",language==="zh"?"安全控制比較表":"Security control comparison");document.querySelector(".role-tabs").setAttribute("aria-label",language==="zh"?"學習路徑起始角色":"Learning path starting role");renderPhase(document.querySelector(".phase-tabs button.active")?.dataset.phase||"off");renderEvidence(document.querySelector("#evidenceLadder button.active")?.dataset.level||0);renderRole(document.querySelector(".role-tabs button.active")?.dataset.role||"foundation");renderCertification();localStorage.setItem("nvm-language",language)}
function renderPhase(id){const p=phases[id];document.querySelectorAll(".phase-tabs button").forEach(b=>{const a=b.dataset.phase===id;b.classList.toggle("active",a);b.setAttribute("aria-pressed",a)});document.querySelector("#windowDetail").innerHTML=`<span class="state">${p.number}</span><h3>${t(p.title)}</h3><p>${t(p.text)}</p><div class="detail-grid"><div><small>SENSITIVE ASSET</small><b>${t(p.asset)}</b></div><div><small>ATTACK METHOD</small><b>${t(p.method)}</b></div><div><small>TEST QUESTION</small><b>${t(p.question)}</b></div><div><small>EXPECTED OUTCOME</small><b>${t(p.outcome)}</b></div></div>`;document.querySelector("#keyState").textContent=p.key;document.querySelector("#resultState").textContent=p.result;document.querySelector("#windowVisual").classList.toggle("active",p.active)}
function renderEvidence(level=0){const n=Number(level);const item=assuranceMaturity[n];document.querySelector("#evidenceLadder").innerHTML=assuranceMaturity.map((e,i)=>`<button data-level="${i}" class="${i===n?'active':''}" aria-pressed="${i===n}"><small>M${i+1}</small><b>${e.name}</b></button>`).join("");document.querySelector("#evidenceDetail").innerHTML=`<div><p class="kicker">MATURITY M${n+1}</p><h3>${t(item.title)}</h3></div><p>${t(item.text)}</p><ul>${t(item.items).map(x=>`<li>${x}</li>`).join("")}</ul>`}
function renderRole(role){document.querySelectorAll(".role-tabs button").forEach(b=>{const active=b.dataset.role===role;b.classList.toggle("active",active);b.setAttribute("aria-pressed",active)});const order=["foundation","practitioner","evaluator","decision"],start=order.indexOf(role),items=[...order.slice(start),...order.slice(0,start)];document.querySelector("#rolePath").innerHTML=items.map((key,i)=>{const r=roleContent[key];return `<article><span>0${i+1} · ${key.toUpperCase()}</span><h3>${t(r[0])}</h3><p>${t(r[1])}</p><b>OUTPUT · ${r[2]}</b></article>`}).join("")}
function renderCertification(){const target=document.querySelector("#targetSelect").value,market=document.querySelector("#marketSelect").value,goal=document.querySelector("#goalSelect").value;let schemes=[];if(market==="iot")schemes=["SESIP","PSA Certified","Common Criteria"];if(market==="auto")schemes=["ISO/SAE 21434 evidence","Common Criteria","UN R155/R156 context"];if(market==="payment")schemes=["Common Criteria","EMVCo","GlobalPlatform"];if(market==="general")schemes=["Independent evaluation","Common Criteria","Internal assurance case"];const scope=target==="ip"?L("建立可由 SoC／產品重用的 IP evidence package；先確認 scheme 是否接受 compositional reuse。","Build an IP evidence package reusable by SoC/product teams; confirm whether the scheme accepts compositional reuse."):target==="soc"?L("把 IP 證據納入 secure IC／SoC TOE，補上 integration、firmware、debug 與 lifecycle 控制。","Bring IP evidence into the secure IC/SoC TOE and cover integration, firmware, debug and lifecycle controls."):L("從裝置 threat model 回推 IP 與 SoC 證據，並涵蓋供應鏈、更新與營運要求。","Trace device threats back to IP and SoC evidence, including supply-chain, update and operational requirements.");const strength=goal==="high"?L("以認可實驗室與正式 scheme scope 為目標。","Target an accredited lab and formal scheme scope."):goal==="reuse"?L("優先建立版本化、可組合與可移轉的 evidence。","Prioritize versioned, composable and transferable evidence."):L("先完成 threat model、design review 與 pre-certification gap assessment。","Start with threat modeling, design review and a pre-certification gap assessment.");document.querySelector("#certResult").innerHTML=`<span class="route">DIRECTIONAL ROUTE</span><h3>${schemes[0]}</h3><p>${t(scope)} ${t(strength)}</p><div class="cert-tags">${schemes.map(s=>`<span>${s}</span>`).join("")}</div><p class="cert-warning">${language==="zh"?"需要確認：TOE、protection profile、assurance level、lab accreditation、產品版本與證據重用規則。此結果不表示已認證。":"Confirm TOE, protection profile, assurance level, lab accreditation, product version and evidence-reuse rules. This result does not indicate certification."}</p>`}

document.querySelector("#languageToggle").addEventListener("click",()=>{language=language==="zh"?"en":"zh";applyLanguage()});document.querySelector(".phase-tabs").addEventListener("click",e=>{const b=e.target.closest("button[data-phase]");if(b)renderPhase(b.dataset.phase)});document.querySelector("#evidenceLadder").addEventListener("click",e=>{const b=e.target.closest("button[data-level]");if(b)renderEvidence(b.dataset.level)});document.querySelector(".role-tabs").addEventListener("click",e=>{const b=e.target.closest("button[data-role]");if(b)renderRole(b.dataset.role)});document.querySelector("#certForm").addEventListener("change",renderCertification);window.addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector("#progressBar").style.width=`${max>0?scrollY/max*100:0}%`});

const primaryNav = document.querySelector("#primaryNav");
const menuToggle = document.querySelector("#menuToggle");
const navLinks = [...primaryNav.querySelectorAll('a[href^="#"]')];
const navSections = navLinks.map(link => document.querySelector(link.hash)).filter(Boolean);
const setCurrentSection = id => navLinks.forEach(link => {
  const current = link.hash === `#${id}`;
  if (current) link.setAttribute("aria-current", "location");
  else link.removeAttribute("aria-current");
});
const closeMenu = ({ restoreFocus = false } = {}) => {
  primaryNav.classList.remove("open");
  menuToggle.classList.remove("open");
  menuToggle.setAttribute("aria-expanded", "false");
  if (restoreFocus) menuToggle.focus();
};
menuToggle.addEventListener("click", () => {
  const open = !primaryNav.classList.contains("open");
  primaryNav.classList.toggle("open", open);
  menuToggle.classList.toggle("open", open);
  menuToggle.setAttribute("aria-expanded", String(open));
  if (open) navLinks[0]?.focus();
});
navLinks.forEach(link => link.addEventListener("click", () => closeMenu()));
document.addEventListener("keydown", event => {
  if (event.key === "Escape" && primaryNav.classList.contains("open")) closeMenu({ restoreFocus: true });
});
const sectionObserver = new IntersectionObserver(entries => {
  const current = entries.filter(entry => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];
  if (current) setCurrentSection(current.target.id);
}, { rootMargin: "-20% 0px -65% 0px", threshold: [0.05, 0.2, 0.5] });
navSections.forEach(section => sectionObserver.observe(section));
const initialSection = location.hash.slice(1);
if (navSections.some(section => section.id === initialSection)) setCurrentSection(initialSection);
renderEvidence(0);renderRole("foundation");applyLanguage();
