import fs from 'node:fs';
import path from 'node:path';
import { bitcellFigure } from './NVM專業元件圖.mjs';
const root=path.resolve(import.meta.dirname,'..');
const check=process.argv.includes('--check');
const sourceCount=JSON.parse(fs.readFileSync(path.join(root,'data/NVM知識資料英文.json'),'utf8')).sources.length;
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bi=(zh,en)=>`<span data-lang="en">${escape(en)}</span><span data-lang="zh">${escape(zh)}</span>`;
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
const layers=[
 {id:'foundations',number:'01',zh:'物理與技術',en:'Physics and Technology',descZh:'先理解狀態存在哪裡，再比較讀取、寫入、可靠度與製程代價。',descEn:'Begin with the stored state. Then compare readout, writing, reliability, and process cost.',items:[
 ['F3','NVM技術全景.html','NVM 技術全景','NVM Technology Atlas','十五個技術專題：逐格操作圖、專利原始附圖、四層限制與年度路線圖。','Fifteen technology studies: operation sequences, original patent drawings, four layers of limits, and annual roadmaps.','15 technologies · 19 patents','十五個技術 · 十九件專利'],
 ['F1','memory-physics.html','位元單元物理與可靠度','Bitcell Physics and Reliability','從電荷、電阻及讀取路徑，理解保持、耐久與可觀察性。','Understand retention, endurance, and observability through charge, resistance, and read paths.','Read paths · Physical limits','讀取路徑 · 物理限制'],
 ['F2','technology-comparison.html','架構選型比較','Technology Selection Matrix','以資料生命週期與系統需求，評估記憶體家族與整合邊界。','Evaluate memory families and integration boundaries against data lifecycle and system requirements.','Selection · Integration','技術選擇 · 系統整合']
 ]},
 {id:'architecture',number:'02',zh:'安全架構',en:'Security Architecture',descZh:'把儲存媒體、秘密、信任根與可驗證的安全邊界分開推理。',descEn:'Reason separately about the storage medium, secrets, roots of trust, and verifiable security boundaries.',items:[
 ['A1','secure-storage.html','安全儲存架構','Secure Storage Architecture','SRAM PUF、金鑰重建、加密與控制器的責任邊界。','SRAM PUF, key reconstruction, encryption, and controller responsibilities.','Key lifecycle · Architecture','金鑰生命週期 · 架構'],
 ['A2','security-assurance.html','安全保證與信任根','Security Assurance and Roots of Trust','威脅模型、攻擊面、測試與認證證據如何接到系統主張。','Connect threat models, attack surfaces, tests, and certification evidence to system claims.','Threats · Assurance','威脅模型 · 安全保證']
 ]},
 {id:'applications',number:'03',zh:'應用與整合',en:'Applications and Integration',descZh:'從晶片要保存的狀態出發，辨別不同應用真正需要的條件。',descEn:'Start with the state a chip must preserve, then identify the conditions each application actually requires.',items:[
 ['D1','ai-nvm-opportunities.html','AI 系統與先進節點','AI Systems and Advanced Nodes','加速器、chiplet 與記憶體系統中的持久狀態需求。','Persistent-state requirements in accelerators, chiplets, and memory systems.','AI · Chiplets · State','AI · Chiplet · 狀態'],
 ['D2','iot-mcu-envm.html','低功耗 IoT 與 MCU','Low-Power IoT and MCU eNVM','程式碼、校準、更新與待機能量的整體取捨。','System tradeoffs in code, calibration, updates, and standby energy.','Code · Updates · Energy','程式碼 · 更新 · 能量'],
 ['D3','automotive-nvm.html','車用 NVM','Automotive NVM','溫度、使用任務與可靠度證據如何限制技術選擇。','How temperature, mission profiles, and reliability evidence constrain technology choice.','Temperature · Reliability','溫度 · 可靠度'],
 ['D4','specialty-nvm.html','特種製程與 BCD','Specialty Processes and BCD','電源管理、高壓驅動與感測器的校準及配置資料。','Trim and configuration state in power management, high-voltage drivers, and sensors.','PMIC · Drivers · Sensors','電源管理 · 驅動 · 感測']
 ]},
 {id:'resources',number:'04',zh:'證據與工作資源',en:'Evidence and Working Resources',descZh:'從論點回到公開文件，再把已保留條件的內容整理成可重用的材料。',descEn:'Trace conclusions to public documents, then reuse material together with its conditions.',items:[
 ['R1','memory-evidence.html','證據總帳','Evidence Ledger','逐筆檢視來源、可支持的主張與仍需驗證的範圍。','Inspect source records, supported claims, and remaining verification boundaries.','Primary sources','第一手來源'],
 ['R2','whitepaper/index.html','白皮書決策工作台','Whitepaper Decision Studio','以可檢查的狀態需求與選型條件組織架構材料。','Organize architecture material around inspectable state requirements and selection conditions.','Decision tools','決策工具'],
 ['R3','briefing/index.html','技術簡報與講稿','Technical Briefings and Talk Tracks','既有簡報、講稿及其來源入口。','Existing presentation material, talk tracks, and their source entry points.','Presentations','簡報資源'],
 ['R4','oip-secure-storage.html','OIP 安全儲存專頁','OIP Secure Storage Brief','SRAM PUF 與安全儲存的展會論述、架構和證據邊界。','Event narrative, architecture, and evidence boundaries for SRAM PUF and secure storage.','OIP · Secure storage','OIP · 安全儲存']
 ]}
];
const row=item=>`<a class="knowledge-row" href="${item[1]}"><span class="knowledge-id">${item[0]}</span><div><h3>${bi(item[2],item[3])}</h3><p>${bi(item[4],item[5])}</p></div><span class="knowledge-meta">${bi(item[7],item[6])}</span>${arrow}</a>`;
const figure=(id,title)=>`<div data-lang="en">${bitcellFigure(id,title,'en',true)}</div><div data-lang="zh">${bitcellFigure(id,title,'zh',true)}</div>`;
const html=`<!doctype html>
<html lang="en" data-language="en" data-title-en="NVM Knowledge Hub — Physics, Technology, and Architecture" data-title-zh="NVM 知識中心 — 物理、技術與架構"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="A source-linked engineering reference for nonvolatile memory: bitcell physics, technology tradeoffs, foundry roadmaps, security architecture, and system applications."><meta name="theme-color" content="#102b40"><title>NVM Knowledge Hub — Physics, Technology, and Architecture</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+TC:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="知識中心首頁.css?v=20260910"><link rel="stylesheet" href="NVM專業元件圖.css?v=20260910"><script src="site-language.js?v=20260910-bilingual"></script></head>
<body class="hub-reading-home" data-pov-contract-id="POV-NVM-WEB-2026-08-29" data-pov-scope-id="POV-NVM-HUB-NEUTRAL-2026-08-29" data-artifact-mode="neutral-editorial" data-accountable-owner-key="sam-huang"><a class="skip-link" href="#main-content">${bi('跳至主要內容','Skip to Main Content')}</a>
<header class="knowledge-header"><a class="brand" href="index.html" aria-label="NVM Knowledge Hub Home" data-aria-en="NVM Knowledge Hub Home" data-aria-zh="NVM 知識中心首頁"><span class="knowledge-mark">NVM</span><span class="knowledge-wordmark">${bi('知識中心','Knowledge Hub')}</span></a><nav aria-label="Primary navigation" data-aria-en="Primary navigation" data-aria-zh="主要導覽"><a href="NVM技術全景.html">${bi('技術全景','Technology Atlas')}</a><a href="NVM技術全景.html#foundry">${bi('路線圖','Roadmaps')}</a><a href="memory-evidence.html">${bi('證據','Evidence')}</a></nav><div class="knowledge-controls"><button id="searchTrigger" class="search-trigger" type="button" aria-label="Search the knowledge hub" data-aria-en="Search the knowledge hub" data-aria-zh="搜尋知識中心" aria-haspopup="dialog" aria-controls="searchOverlay" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><span>${bi('搜尋','Search')}</span><kbd>Ctrl+K</kbd></button><button type="button" id="languageToggle" class="language-toggle" aria-label="Switch to Traditional Chinese"><b data-lang-option="en">EN</b><i>/</i><b data-lang-option="zh" lang="zh-Hant">中文</b></button></div></header>
<div id="searchOverlay" class="search-overlay" role="dialog" aria-modal="true" aria-hidden="true" aria-label="Search the knowledge hub" data-aria-en="Search the knowledge hub" data-aria-zh="搜尋知識中心"><div class="search-modal"><div class="search-input-row"><input id="searchInput" type="search" autocomplete="off" aria-label="Search topics and evidence" data-aria-en="Search topics and evidence" data-aria-zh="搜尋主題與證據" aria-describedby="searchStatus" data-placeholder-en="Technology, mechanism, company, or source ID" data-placeholder-zh="技術、機制、公司或來源編號"><button type="button" id="searchClose" aria-label="Close search" data-aria-en="Close search" data-aria-zh="關閉搜尋">×</button></div><p id="searchStatus" class="search-status" role="status" aria-live="polite"></p><div id="searchResults" class="search-results"></div></div></div>
<main id="main-content"><section class="knowledge-hero"><div class="knowledge-hero-copy"><p class="eyebrow">${bi('非揮發性記憶體 · 工程知識參考','NONVOLATILE MEMORY · ENGINEERING REFERENCE')}</p><h1>${bi('理解位元單元，設計完整系統','Understand the Cell. Design the System')}</h1><p class="knowledge-intro">${bi('從材料中的儲存狀態，到晶片與系統的工程選擇。以公開來源、具名實作與清楚的條件，連接 NVM 物理、技術與架構。','From a state stored in a material to an engineering choice in a system. Connect NVM physics, technologies, and architecture through public sources, named implementations, and explicit conditions.')}</p><div class="knowledge-actions"><a class="knowledge-primary" href="NVM技術全景.html">${bi('進入技術全景','Explore the Technology Atlas')}${arrow}</a><a href="#layer-foundations">${bi('瀏覽知識地圖','Browse the Knowledge Map')}${arrow}</a></div><div class="knowledge-facts"><div><b>15</b><span>${bi('完整技術專題','Technology Studies')}</span></div><div><b>19</b><span>${bi('代表專利','Representative Patents')}</span></div><div><b>${sourceCount}</b><span>${bi('全景來源紀錄','Atlas Source Records')}</span></div></div></div><figure class="knowledge-hero-art"><div class="figure-overline"><span>${bi('儲存物理 · 結構剖視','STORAGE PHYSICS · DEVICE CUTAWAY')}</span><span>01 / NAND</span></div>${figure('nand','3D Charge-Trap NAND')}<figcaption><strong>${bi('垂直堆疊，徑向儲存。','Vertical Stacking. Radial Storage.')}</strong><span>${bi('字元線、記憶膜與垂直通道的原理剖視。非比例示意。','A principle cutaway of word lines, memory films, and the vertical channel. Not to scale.')}</span><a href="NVM技術全景.html#topic-nand">${bi('閱讀 NAND 專題','Read the NAND Study')}${arrow}</a></figcaption></figure></section>
<section class="knowledge-focus" aria-label="Featured research" data-aria-en="Featured research" data-aria-zh="重點研究"><a href="NVM技術全景.html#foundry"><span class="focus-kicker">${bi('年度追蹤','FOUNDRY TRACKER')}</span><h2>GLOBALFOUNDRIES / TSMC</h2><p>${bi('MRAM、ReRAM：宣布、驗證與量產分開核對。','MRAM and ReRAM: distinguish announcements, qualification, and volume production.')}</p>${arrow}</a><a href="NVM技術全景.html#comparison"><span class="focus-kicker">${bi('比較方法','COMPARISON METHOD')}</span><h2>${bi('數值必須保留條件','Numbers Need Their Conditions')}</h2><p>${bi('歷史課程表、現況修正與六個具名實作案例。','Historical course data, current corrections, and six named implementation examples.')}</p>${arrow}</a><a href="NVM技術全景.html#system-scm"><span class="focus-kicker">${bi('系統邊界','SYSTEM BOUNDARY')}</span><h2>${bi('媒體到持久性','From Media to Persistence')}</h2><p>${bi('SCM、CXL、失電一致性與完整系統責任。','SCM, CXL, power-failure consistency, and complete system responsibilities.')}</p>${arrow}</a></section>
<div class="knowledge-map" id="topics"><nav class="hub-rail-nav" aria-label="Knowledge map sections" data-aria-en="Knowledge map sections" data-aria-zh="知識地圖章節">${layers.map(layer=>`<a class="hub-rail-btn" href="#layer-${layer.id}" data-target="layer-${layer.id}"><span>${layer.number}</span>${bi(layer.zh,layer.en)}</a>`).join('')}</nav>${layers.map(layer=>`<section class="knowledge-section" id="layer-${layer.id}"><header><span class="section-number">${layer.number}</span><div><h2>${bi(layer.zh,layer.en)}</h2><p>${bi(layer.descZh,layer.descEn)}</p></div></header><div class="knowledge-list">${layer.items.map(row).join('')}</div></section>`).join('')}</div>
<section class="knowledge-method"><div><p class="eyebrow">${bi('如何使用這個知識中心','HOW TO USE THIS REFERENCE')}</p><h2>${bi('由原理到選擇，每一步都保留證據','Keep the Evidence with the Engineering Decision')}</h2></div><ol><li><b>01</b><div><h3>${bi('辨別物理與架構','Separate Physics and Architecture')}</h3><p>${bi('先看儲存變數與操作，再確認陣列與系統的代價。','Start with the stored variable and operation, then account for array and system costs.')}</p></div></li><li><b>02</b><div><h3>${bi('核對具名實作','Check a Named Implementation')}</h3><p>${bi('速度、耐久、保持與量產，必須綁定相同產品及條件。','Bind speed, endurance, retention, and production status to the same implementation and conditions.')}</p></div></li><li><b>03</b><div><h3>${bi('保留來源再重用','Reuse the Content with Its Sources')}</h3><p>${bi('中英文資料可下載，作為後續簡報或教材的共同來源。','Download the English or Chinese study data as a shared source for presentations and teaching.')}</p></div></li></ol></section></main>
<footer class="knowledge-footer"><a class="brand" href="index.html"><span class="knowledge-mark">NVM</span><span>${bi('知識中心','Knowledge Hub')}</span></a><p>${bi('公開來源研究 · 工程脈絡與證據邊界','Public-source research · Engineering context and evidence boundaries')}</p><div><a href="NVM技術全景.html#sources">${bi('全景來源與資料下載','Atlas Sources and Downloads')}</a><a href="memory-evidence.html">${bi('證據總帳','Evidence Ledger')}</a><a href="https://samhuang68.github.io/">${bi('專案主站','Project Portal')}</a></div></footer><script src="data/NVM搜尋索引.js?v=20260910-bilingual"></script><script src="hub.js?v=20260910-bilingual"></script><script src="搜尋控制器.js?v=20260910-bilingual"></script><script src="首頁導覽.js?v=20260910"></script></body></html>\n`;
const file=path.join(root,'index.html');
if(check){if(fs.readFileSync(file,'utf8')!==html)throw new Error('首頁與共用資料未同步');}
else fs.writeFileSync(file,html,'utf8');
console.log('通過：雙語首頁、四組知識導覽、十三個資源入口與專業元件圖同步');
