import fs from 'node:fs';
import path from 'node:path';
import { physicsIndex, researchShowcase } from './NVM視覺索引.mjs';
const root=path.resolve(import.meta.dirname,'..');
const check=process.argv.includes('--check');
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bi=(zh,en)=>`<span data-lang="en">${escape(en)}</span><span data-lang="zh">${escape(zh)}</span>`;
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
const catalog=JSON.parse(fs.readFileSync(path.join(root,'data/NVM知識目錄.json'),'utf8'));
const research=JSON.parse(fs.readFileSync(path.join(root,'data/NVM產研比較.json'),'utf8'));
const researchEn=JSON.parse(fs.readFileSync(path.join(root,'data/NVM產研比較英文.json'),'utf8'));
const researchCounts={routes:research.landscape.length,families:new Set(research.landscape.map(r=>r.family)).size,profiles:research.profiles.length};
const layers=catalog.sections.map(section=>({id:section.id,number:section.number,zh:section.titleZh,en:section.titleEn,descZh:section.descriptionZh,descEn:section.descriptionEn,items:section.items.map(item=>[item.id,item.url,item.titleZh,item.titleEn,item.descriptionZh,item.descriptionEn,item.metaEn,item.metaZh])}));
const row=(item,index)=>`<a class="knowledge-row"${item[0]==='A1'?' id="layer-architecture"':''} href="${item[1]}"><span class="knowledge-id">${String(index+1).padStart(2,'0')}</span><div><h3>${bi(item[2],item[3])}</h3><p>${bi(item[4],item[5])}</p></div><span class="knowledge-meta">${bi(item[7],item[6])}</span>${arrow}</a>`;
const html=`<!doctype html>
<html lang="en" data-language="en" data-title-en="NVM Knowledge Hub — Physics, Technology, and Architecture" data-title-zh="NVM 知識中心 — 物理、技術與架構"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="A source-linked engineering reference for nonvolatile memory: bitcell physics, technology tradeoffs, foundry roadmaps, security architecture, and system applications."><meta name="theme-color" content="#102b40"><title>NVM Knowledge Hub — Physics, Technology, and Architecture</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+TC:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="知識中心首頁.css?v=20260910-library"><link rel="stylesheet" href="商用閱讀介面.css?v=20260911-editorial7"><script src="site-language.js?v=20260910-bilingual"></script></head>
<body class="hub-reading-home" data-pov-contract-id="POV-NVM-WEB-2026-08-29" data-pov-scope-id="POV-NVM-HUB-NEUTRAL-2026-08-29" data-artifact-mode="neutral-editorial" data-accountable-owner-key="sam-huang"><a class="skip-link" href="#main-content">${bi('跳至主要內容','Skip to Main Content')}</a>
<header class="knowledge-header"><a class="brand" href="index.html" aria-label="NVM Knowledge Hub Home" data-aria-en="NVM Knowledge Hub Home" data-aria-zh="NVM 知識中心首頁"><span class="knowledge-mark">NVM</span><span class="knowledge-wordmark">${bi('知識中心','Knowledge Hub')}</span></a><nav aria-label="Primary navigation" data-aria-en="Primary navigation" data-aria-zh="主要導覽">${layers.map(layer=>`<a href="#layer-${layer.id}">${bi(layer.zh,layer.en)}</a>`).join('')}</nav><div class="knowledge-controls"><button id="searchTrigger" class="search-trigger" type="button" aria-label="Search the knowledge hub" data-aria-en="Search the knowledge hub" data-aria-zh="搜尋知識中心" aria-haspopup="dialog" aria-controls="searchOverlay" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><span>${bi('搜尋','Search')}</span><kbd>Ctrl+K</kbd></button><button type="button" id="languageToggle" class="language-toggle" aria-label="Switch to Traditional Chinese"><b data-lang-option="en">EN</b><i>/</i><b data-lang-option="zh" lang="zh-Hant">中文</b></button></div></header>
<div id="searchOverlay" class="search-overlay" role="dialog" aria-modal="true" aria-hidden="true" aria-label="Search the knowledge hub" data-aria-en="Search the knowledge hub" data-aria-zh="搜尋知識中心"><div class="search-modal"><div class="search-input-row"><input id="searchInput" type="search" autocomplete="off" aria-label="Search topics and evidence" data-aria-en="Search topics and evidence" data-aria-zh="搜尋主題與證據" aria-describedby="searchStatus" data-placeholder-en="Technology, mechanism, company, or source ID" data-placeholder-zh="技術、機制、公司或來源編號"><button type="button" id="searchClose" aria-label="Close search" data-aria-en="Close search" data-aria-zh="關閉搜尋">×</button></div><p id="searchStatus" class="search-status" role="status" aria-live="polite"></p><div id="searchResults" class="search-results"></div></div></div>
<main id="main-content"><section class="knowledge-editorial-hero"><div class="knowledge-editorial-inner"><header class="knowledge-intro-header"><p class="eyebrow">${bi('從物理原理到具名實作','FROM DEVICE PHYSICS TO NAMED IMPLEMENTATIONS')}</p><h1>${bi(catalog.titleZh,catalog.titleEn)}</h1><p class="knowledge-intro">${bi(catalog.introZh,catalog.introEn)}</p><div class="knowledge-actions"><a class="knowledge-primary" href="NVM技術全景.html#ecosystem">${bi('探索產業與研究地圖','Explore the Industry Map')}${arrow}</a><a href="#layer-foundations">${bi('從技術基礎開始','Start with the Fundamentals')}${arrow}</a></div></header>${physicsIndex(bi)}</div><dl class="knowledge-coverage"><div><dt>${bi('具名技術路線','Named Technology Routes')}</dt><dd>${researchCounts.routes}</dd></div><div><dt>${bi('產研技術家族','Industry and Research Families')}</dt><dd>${researchCounts.families}</dd></div><div><dt>${bi('產研深度專題','In-Depth Studies')}</dt><dd>${researchCounts.profiles}</dd></div><div class="knowledge-coverage-note"><dt>${bi('同一份資料，兩種閱讀語言','One Reference, Two Languages')}</dt><dd>${bi('英文／繁體中文','English / Traditional Chinese')}</dd></div></dl></section>
<div class="knowledge-map" id="topics"><nav class="hub-rail-nav" aria-label="Knowledge map sections" data-aria-en="Knowledge map sections" data-aria-zh="知識地圖章節">${layers.map(layer=>`<a class="hub-rail-btn" href="#layer-${layer.id}" data-target="layer-${layer.id}"><span>${layer.number}</span>${bi(layer.zh,layer.en)}</a>`).join('')}</nav>${layers.map(layer=>`<section class="knowledge-section" id="layer-${layer.id}"><header><span class="section-number">${layer.number}</span><div><h2>${bi(layer.zh,layer.en)}</h2><p>${bi(layer.descZh,layer.descEn)}</p></div></header><div class="knowledge-list">${layer.items.map(row).join('')}</div></section>`).join('')}</div>
${researchShowcase(research,researchEn,bi)}
<section class="knowledge-method"><div><p class="eyebrow">${bi('如何使用這個知識中心','HOW TO USE THIS REFERENCE')}</p><h2>${bi('由原理到選擇，每一步都保留證據','Keep the Evidence with the Engineering Decision')}</h2></div><ol><li><b>01</b><div><h3>${bi('辨別物理與架構','Separate Physics and Architecture')}</h3><p>${bi('先看儲存變數與操作，再確認陣列與系統的代價。','Start with the stored variable and operation, then account for array and system costs.')}</p></div></li><li><b>02</b><div><h3>${bi('核對具名實作','Check a Named Implementation')}</h3><p>${bi('速度、耐久、保持與量產，必須綁定相同產品及條件。','Bind speed, endurance, retention, and production status to the same implementation and conditions.')}</p></div></li><li><b>03</b><div><h3>${bi('保留來源再重用','Reuse the Content with Its Sources')}</h3><p>${bi('中英文資料可下載，作為後續簡報或教材的共同來源。','Download the English or Chinese study data as a shared source for presentations and teaching.')}</p></div></li></ol></section></main>
<footer class="knowledge-footer"><a class="brand" href="index.html"><span class="knowledge-mark">NVM</span><span>${bi('知識中心','Knowledge Hub')}</span></a><p>${bi('公開來源研究 · 工程脈絡與證據邊界','Public-source research · Engineering context and evidence boundaries')}</p><div><a href="NVM技術全景.html#sources">${bi('全景來源與資料下載','Atlas Sources and Downloads')}</a><a href="memory-evidence.html">${bi('證據總帳','Evidence Ledger')}</a><a href="https://samhuang68.github.io/">${bi('專案主站','Project Portal')}</a></div></footer><script src="data/NVM搜尋索引.js?v=20260910-bilingual"></script><script src="hub.js?v=20260910-bilingual"></script><script src="搜尋控制器.js?v=20260910-bilingual"></script><script src="首頁導覽.js?v=20260911-editorial7"></script></body></html>\n`;
const file=path.join(root,'index.html');
if(check){if(fs.readFileSync(file,'utf8')!==html)throw new Error('首頁與共用資料未同步');}
else fs.writeFileSync(file,html,'utf8');
console.log(`通過：雙語知識中心首頁、${layers.length} 類目錄與 ${layers.reduce((n,layer)=>n+layer.items.length,0)} 個主題入口同步`);
