import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
import { startTestServer } from './驗證伺服器.mjs';
import { captureLanguageSurface, assessLanguageSurface } from './雙語畫面契約.mjs';

const root = path.resolve(import.meta.dirname, '..');
const output = path.join(root, 'qa', 'sram-repair');
await fs.mkdir(output, { recursive: true });
const server = process.env.NVM_QA_BASE ? null : await startTestServer(root);
const base = process.env.NVM_QA_BASE || server.base;
const browser = await chromium.launch({ headless: true, ...(process.env.NVM_QA_EXECUTABLE ? { executablePath: process.env.NVM_QA_EXECUTABLE } : {}) });
const context = await browser.newContext({ serviceWorkers: 'block', viewport: { width: 1440, height: 1050 }, acceptDownloads: true });
await context.route('**/*', route => new URL(route.request().url()).origin === new URL(base).origin ? route.continue() : route.abort());
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const text = id => page.locator('#' + id).textContent();
const equals = async (id, expected) => assert.equal(await text(id), expected, id);
const language = async expected => assert.deepEqual(assessLanguageSurface(await page.evaluate(captureLanguageSurface), expected), [], expected + ' language surface');
try {
  await page.goto(new URL('index.html?lang=en', base).href);
  await page.locator('#layer-applications a[href="sram-repair.html"]').click();
  await page.waitForSelector('#otp-overhead');
  await equals('raw-exact', '16,000,000 bits');
  await equals('payload-exact', '160,000 bits');
  assert.match(await text('payload-bytes'), /^20,000 B/);
  await language('en');
  await page.screenshot({ path: path.join(output, 'desktop-en.png'), fullPage: true });
  await page.locator('#otp-overhead').fill('12.5');
  await page.locator('#otp-reserve').fill('10');
  await page.locator('#otp-block').fill('1024');
  await page.locator('#efuse-block').fill('4096');
  assert.equal(await page.locator('[data-value="otp-allocated"]').textContent(), '198,656 bits');
  assert.equal(await page.locator('[data-value="efuse-allocated"]').textContent(), '163,840 bits');
  await page.locator('.language-toggle').click();
  await language('zh');
  assert.equal(await page.locator('#otp-overhead').inputValue(), '12.5');
  await equals('payload-exact', '160,000 bits');
  await page.locator('#otp-overhead').fill('20');
  assert.equal(await page.locator('[data-value="otp-allocated"]').textContent(), '211,968 bits');
  await page.locator('#load-example').click();
  await page.locator('#mode').selectOption('retained');
  assert.equal(await page.locator('#compression').inputValue(), '1');
  await equals('payload-exact', '160,000 bits');
  await page.locator('#mode').selectOption('reduction');
  assert.equal(await page.locator('#compression').inputValue(), '99');
  await equals('payload-exact', '160,000 bits');
  await page.locator('#compression').fill('100');
  assert.equal(await page.locator('#export').isDisabled(), true);
  await equals('payload-exact', '—');
  assert.match(await text('compression-error'), /100%/);
  await language('zh');
  await page.locator('.language-toggle').click();
  await language('en');
  assert.match(await text('compression-error'), /less than 100%/);
  await page.locator('#reset').click();
  await page.locator('#unit').selectOption('Gib');
  await equals('raw-exact', '17,179,870 bits');
  await equals('payload-exact', '171,799 bits');
  await page.locator('[data-capacity="32"]').click();
  await equals('payload-exact', '320,000 bits');
  await page.locator('#repair').fill('0.1%');
  await equals('payload-exact', '320,000 bits');
  await page.locator('#repair').fill('1/0');
  assert.equal(await page.locator('#export').isDisabled(), true);
  await page.locator('#load-example').click();
  const before = await page.locator('#chart svg path').first().getAttribute('d');
  await page.locator('#scale-linear').click();
  assert.equal(await page.locator('#scale-linear').getAttribute('aria-pressed'), 'true');
  assert.notEqual(await page.locator('#chart svg path').first().getAttribute('d'), before);
  await page.locator('#compression-slider').fill('25');
  await equals('payload-exact', '1,600,000 bits');
  await page.locator('#load-example').click();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadPromise;
  const file = path.join(output, download.suggestedFilename());
  await download.saveAs(file);
  const csv = await fs.readFile(file, 'utf8');
  assert.match(csv, /"Compressed payload","160000","bits"/);
  assert.match(csv, /"Allocated capacity \(bits\)","160000","160000"/);
  await page.locator('#method summary').click();
  await language('en');
  await page.locator('.language-toggle').click();
  await language('zh');
  await page.screenshot({ path: path.join(output, 'desktop-zh.png'), fullPage: true });
  for (const width of [390, 768]) {
    await page.setViewportSize({ width, height: 844 });
    await page.evaluate(() => window.scrollTo(0, 0));
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No horizontal page overflow at ' + width);
    await page.screenshot({ path: path.join(output, 'mobile-' + width + '.png'), fullPage: true });
    await page.locator('[data-capacity="64"]').click();
    await equals('payload-exact', '640,000 bits');
    await page.locator('#load-example').click();
  }
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.locator('a.brand').click();
  await page.locator('#searchTrigger').click();
  const search = page.locator('#searchOverlay input[type="search"]');
  await search.fill('SRAM repair');
  await page.locator('#searchResults a[href*="sram-repair.html"]').waitFor();
  assert.deepEqual(errors, []);
  const manifest = await fs.readFile(path.join(root, 'data/offline-manifest.js'), 'utf8');
  for (const asset of ['sram-repair.html', 'sram-repair.js', 'sram-repair-model.js', 'sram-repair.css']) assert.ok(manifest.includes('"' + asset + '"'), asset + ' in offline manifest');
  console.log('SRAM browser checks passed: application entry, search, defaults, exact allocations, unit conversion, compression modes, slider, chart, invalid inputs, bilingual state preservation, CSV and responsive layout.');
} finally {
  await context.close();
  await browser.close();
  if (server) await server.close();
}
